### ISSUE TITLE
Design Note

### ISSUE THREAD

**Issue by AnuthinWongsunkakon** [cadsondemak/Krub#2]
Could you please start leaving a design note here. It does not have to be a problem. It could be a memo or open discussion.

**Comment by davelab6** [comment]
I would like to review the design :)

**Comment by AnuthinWongsunkakon** [comment]
![1376920766-capturejpg-o](https://user-images.githubusercontent.com/36420640/37381521-2dbaf6b8-2770-11e8-9fce-8cc1f72fb843.jpg)

**Comment by AnuthinWongsunkakon** [comment]
![1376920766-capturejpg-o](https://user-images.githubusercontent.com/36420640/37381593-9a16ae9c-2770-11e8-82f2-f6b3d8f2dd69.jpg)
This was taken from Word 2010 ruling on Window. The problem was found in the original TH Krub from Depa. @suppakit- Please note that this should be taking care of in this version.

**Comment by AnuthinWongsunkakon** [comment]
Also the complaint about the line gap value is a bit too small. This found in LibreOffice on Ubuntu. What you see in the screen capture is set at 120%. Personally I think it is too wide though. Maybe somewhat 110% would do? Please note this issue as well along with checking this issue on other platforms.
![1376957375-thkrub-o](https://user-images.githubusercontent.com/36420640/37381626-cae0ece0-2770-11e8-954b-e8e20b0dc556.png)
