### ISSUE TITLE
MM interpolation issues

### ISSUE THREAD

**Issue by m4rc1e** [cadsondemak/Krub#6]
Found this one rather quickly, there may be more.

![screen shot 2018-08-17 at 12 32 48](https://user-images.githubusercontent.com/7525512/44264564-f9499a80-a21a-11e8-9792-a67e0706ff96.png)

**Comment by m4rc1e** [comment]
Happens to the original non narrow form as well

**Comment by m4rc1e** [comment]
@cadsondemakoffice did you fix this?

**Comment by cadsondemakoffice** [comment]
@m4rc1e Thank you for your report, now we have fixed the issue.
